-- AlterTable
ALTER TABLE `profile` ADD COLUMN `aboutPhotoUrl` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `adminPhotoUrl` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `contactPhotoUrl` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `footerPhotoUrl` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `heroPhotoUrl` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `navbarPhotoUrl` VARCHAR(191) NOT NULL DEFAULT '';
